---
- name: Install latest versions of pip packages
  pip:
    name: '{{ item }}'
    executable: 'pip3'
  with_items:
    - anaconda-client
    - argcomplete  # FIXME: via homebrew?
    - clf  # FIXME: via homebrew?
    - eg  # FIXME: via homebrew?
    - emoji  # FIXME: via homebrew?
    - em-keyboard  # FIXME: via homebrew?
    - # FIXME: flake8 stuff via homebrew?
    - flake8-bugbear
    - flake8-builtins
    - flake8-coding
    - flake8-commas
    - flake8-comprehensions
    - flake8-debugger
    - flake8-deprecated
    - flake8-docstrings
    - flake8_dodgy
    - flake8-import-order
    - flake8-imports
    - flake8-isort
    - flake8-mutable
    - flake8-pep3101
    - flake8-print
    - flake8-string-format
    - flake8-tidy-imports
    - flake8-todo
    - flake8_tuple
    - hashin  # FIXME: via homebrew?
    - jupyter_contrib_nbextensions
    - jupyterlab
    - ntfy[pid,emoji,slack]  # FIXME: via homebrew?
    - pip-tools  # FIXME: via homebrew?
    - psutil
    - pydocstyle  # FIXME: via homebrew?
    - pyflakes  # FIXME: via homebrew?
    - pylint  # FIXME: via homebrew?
    - pytest  # FIXME: via homebrew?
    - pytest-xdist  # FIXME: via homebrew?
    - rpy2
    # - r-essentials
    - searchcmd
    - slacker
    - tldr  # FIXME: via homebrew?
    - twine
    - uncommitted  # FIXME: via homebrew?
    - yapf  # FIXME: via homebrew?
  become: yes
