---
# The default version of Ruby to be initially installed via rbenv.
rbenv_default_ruby_version: "2.5.1"

# Any global gems to be installed with the default Ruby version.
rbenv_global_gems:
  - bundle-audit
  - bundler # http://bundler.io/
  - danger
  - html-proofer
  - image_optim
  - image_optim_pack
  - jekyll
  - json
  - overcommit # https://github.com/brigade/overcommit
  - rspec
  - rubocop  # https://github.com/bbatsov/rubocop
  - sqlint
  - terminal-notifier
  - travis
  - w3c_validators

# Whether the role should add the line `eval \"$(rbenv init -)\"` to .bash_profile.
# If set to false you'll want to consider adding this line yourself.
rbenv_update_bash_profile: false
